"""empty message

Revision ID: 3c2e5a72cac0
Revises: 7af6fbdf9ce6
Create Date: 2025-11-01 13:51:15.301537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2e5a72cac0'
down_revision = '7af6fbdf9ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_products', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reference_products', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
