"""Add company_provided_id and updated_at to equipment

Revision ID: 4c1834ce6278
Revises: 
Create Date: 2025-08-20 19:26:16.858939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1834ce6278'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_provided_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('make', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_equipment_company', 'companies', ['company_id'], ['id'])
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('model')
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('manufacturer', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint('fk_equipment_company', type_='foreignkey')
        batch_op.drop_column('company_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('make')
        batch_op.drop_column('company_provided_id')

    # ### end Alembic commands ###
