"""empty message

Revision ID: 5c1fc736c53b
Revises: 3c2e5a72cac0
Create Date: 2025-11-01 14:16:32.947974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1fc736c53b'
down_revision = '3c2e5a72cac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('last_calibration',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('next_calibration',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('calibration_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('next_calibration_due',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('next_calibration_due',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('calibration_date',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('next_calibration',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('last_calibration',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
