"""empty message

Revision ID: 7af6fbdf9ce6
Revises: dbd8b41f8950
Create Date: 2025-11-01 13:46:15.169494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af6fbdf9ce6'
down_revision = 'dbd8b41f8950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reagents', schema=None) as batch_op:
        batch_op.alter_column('expiry_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reagents', schema=None) as batch_op:
        batch_op.alter_column('expiry_date',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
