"""Add subscription plan to User model

Revision ID: 8878c4182c0a
Revises: 5c1fc736c53b
Create Date: 2025-11-15 19:27:40.598552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8878c4182c0a'
down_revision = '5c1fc736c53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tables in correct order (reverse dependency order)
    
    # First drop tables that have foreign keys to other tables
    op.drop_table('pvr_stage_results')
    op.drop_table('pvr_data')
    op.drop_table('pvp_extracted_stages')
    op.drop_table('pvp_materials')
    op.drop_table('pvp_equipment')
    op.drop_table('pvp_criteria')
    
    # Then drop tables that are referenced by others
    op.drop_table('pvr_report')
    op.drop_table('pvp_template')
    
    # Finally drop independent tables
    with op.batch_alter_table('pv_stage_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_pv_stage_templates_product_type')
    op.drop_table('pv_stage_templates')
    
    # Add subscription columns to users table
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.String(length=50), nullable=True, server_default='free'))
        batch_op.add_column(sa.Column('subscription_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove subscription columns first
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_expiry')
        batch_op.drop_column('subscription_plan')
    
    # Recreate tables in correct order (forward dependency order)
    
    # First create independent tables
    op.create_table('pv_stage_templates',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pv_stage_templates_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('product_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stage_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('activity_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('key_parameters', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('validation_objective', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_optional', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pv_stage_templates_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('pv_stage_templates', schema=None) as batch_op:
        batch_op.create_index('ix_pv_stage_templates_product_type', ['product_type'], unique=False)
    
    # Then create tables that others depend on
    op.create_table('pvp_template',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pvp_template_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('original_filepath', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('product_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('batch_size', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pvp_template_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pvp_template_pkey'),
    sa.UniqueConstraint('template_name', name='pvp_template_template_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    
    op.create_table('pvr_report',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pvp_template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generated_filepath', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('word_filepath', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pvp_template_id'], ['pvp_template.id'], name='pvr_report_pvp_template_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pvr_report_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pvr_report_pkey')
    )
    
    # Finally create tables that depend on others
    op.create_table('pvp_criteria',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pvp_template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('test_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('acceptance_criteria', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pvp_template_id'], ['pvp_template.id'], name='pvp_criteria_pvp_template_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pvp_criteria_pkey')
    )
    
    op.create_table('pvp_equipment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pvp_template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipment_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('equipment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('calibration_status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('calibration_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pvp_template_id'], ['pvp_template.id'], name='pvp_equipment_pvp_template_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pvp_equipment_pkey')
    )
    
    op.create_table('pvp_materials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pvp_template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('material_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('specification', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pvp_template_id'], ['pvp_template.id'], name='pvp_materials_pvp_template_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pvp_materials_pkey')
    )
    
    op.create_table('pvp_extracted_stages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pvp_extracted_stages_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('pvp_template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage_template_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stage_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('equipment_used', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specific_parameters', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('acceptance_criteria', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('test_methods', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('observations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pvp_template_id'], ['pvp_template.id'], name='pvp_extracted_stages_pvp_template_id_fkey'),
    sa.ForeignKeyConstraint(['stage_template_id'], ['pv_stage_templates.id'], name='pvp_extracted_stages_stage_template_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pvp_extracted_stages_pkey'),
    postgresql_ignore_search_path=False
    )
    
    op.create_table('pvr_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pvr_report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('test_result', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pvr_report_id'], ['pvr_report.id'], name='pvr_data_pvr_report_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pvr_data_pkey')
    )
    
    op.create_table('pvr_stage_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pvr_report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extracted_stage_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parameter_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('actual_value', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('acceptance_criteria', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('result_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['extracted_stage_id'], ['pvp_extracted_stages.id'], name='pvr_stage_results_extracted_stage_id_fkey'),
    sa.ForeignKeyConstraint(['pvr_report_id'], ['pvr_report.id'], name='pvr_stage_results_pvr_report_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pvr_stage_results_pkey')
    )
    # ### end Alembic commands ###