"""Initial migration with all PV tables

Revision ID: b18307366ae4
Revises: 
Create Date: 2025-11-07 23:43:36.735199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'b18307366ae4'
down_revision = None
branch_labels = None
depends_on = None


def table_exists(table_name, connection):
    inspector = Inspector.from_engine(connection)
    return table_name in inspector.get_table_names()


def upgrade():
    connection = op.get_bind()

    # Check if the 'documents' table exists using raw SQL
    result = connection.execute(text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_name = 'documents'
        );
    """))
    table_exists = result.scalar()

    # Create the table only if it does not exist
    if not table_exists:
        op.create_table(
            'documents',
            sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
            sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id'), nullable=False),
            sa.Column('company_id', sa.Integer, sa.ForeignKey('companies.id'), nullable=False),
            sa.Column('document_type', sa.String(50), nullable=False),
            sa.Column('document_number', sa.String(100)),
            sa.Column('title', sa.String(300), nullable=False),
            sa.Column('status', sa.String(20), nullable=False),
            sa.Column('stp_file_url', sa.String(500)),
            sa.Column('raw_data_url', sa.String(500)),
            sa.Column('method_analysis_file_url', sa.String(500)),
            sa.Column('generated_doc_url', sa.String(500)),
            sa.Column('generated_excel_url', sa.String(500)),
            sa.Column('document_metadata', sa.Text),
            sa.Column('created_at', sa.DateTime, nullable=False),
            sa.Column('updated_at', sa.DateTime, nullable=False)
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'pv_stage_templates') THEN
            CREATE TABLE pv_stage_templates (
                id SERIAL NOT NULL,
                product_type VARCHAR(50) NOT NULL,
                stage_number INTEGER NOT NULL,
                stage_name VARCHAR(200) NOT NULL,
                activity_description TEXT,
                key_parameters TEXT,
                validation_objective TEXT,
                is_optional BOOLEAN NOT NULL,
                PRIMARY KEY (id)
            );
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'ix_pv_stage_templates_product_type') THEN
            CREATE INDEX ix_pv_stage_templates_product_type ON pv_stage_templates (product_type);
        END IF;
    END $$;
    """)

    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'users') THEN
            CREATE TABLE users (
                id SERIAL NOT NULL,
                firebase_uid VARCHAR(128) NOT NULL,
                email VARCHAR(120) NOT NULL,
                name VARCHAR(100) NOT NULL,
                is_admin BOOLEAN NOT NULL,
                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                last_login TIMESTAMP WITHOUT TIME ZONE,
                password_hash VARCHAR(255),
                PRIMARY KEY (id),
                UNIQUE (email),
                UNIQUE (firebase_uid)
            );
        END IF;
    END $$;
    """)

    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'activity_logs') THEN
            CREATE TABLE activity_logs (
                id SERIAL NOT NULL,
                user_id INTEGER NOT NULL,
                action VARCHAR(100) NOT NULL,
                details TEXT,
                ip_address VARCHAR(45),
                timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id),
                FOREIGN KEY(user_id) REFERENCES users (id)
            );
        END IF;
    END $$;
    """)

    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'companies') THEN
            CREATE TABLE companies (
                id SERIAL NOT NULL,
                user_id INTEGER NOT NULL,
                name VARCHAR(200) NOT NULL,
                address TEXT,
                logo_url VARCHAR(500),
                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id),
                FOREIGN KEY(user_id) REFERENCES users (id)
            );
        END IF;
    END $$;
    """)

    op.create_table('pvp_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('batch_size', sa.String(length=100), nullable=True),
    sa.Column('filepath', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stp_file_url', sa.String(length=500), nullable=True),
    sa.Column('raw_data_url', sa.String(length=500), nullable=True),
    sa.Column('method_analysis_file_url', sa.String(length=500), nullable=True),
    sa.Column('generated_doc_url', sa.String(length=500), nullable=True),
    sa.Column('generated_excel_url', sa.String(length=500), nullable=True),
    sa.Column('document_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_provided_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('calibration_date', sa.DateTime(), nullable=True),
    sa.Column('next_calibration_due', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_equipment_company'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvp_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pvp_template_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('test_name', sa.String(length=200), nullable=True),
    sa.Column('acceptance_criteria', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['pvp_template_id'], ['pvp_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvp_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pvp_template_id', sa.Integer(), nullable=False),
    sa.Column('equipment_name', sa.String(length=200), nullable=False),
    sa.Column('equipment_id', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('calibration_status', sa.String(length=100), nullable=True),
    sa.Column('calibration_date', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['pvp_template_id'], ['pvp_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvp_extracted_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pvp_template_id', sa.Integer(), nullable=False),
    sa.Column('stage_template_id', sa.Integer(), nullable=True),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=200), nullable=False),
    sa.Column('equipment_used', sa.Text(), nullable=True),
    sa.Column('specific_parameters', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('test_methods', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pvp_template_id'], ['pvp_templates.id'], ),
    sa.ForeignKeyConstraint(['stage_template_id'], ['pv_stage_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvp_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pvp_template_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('specification', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['pvp_template_id'], ['pvp_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvr_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pvp_template_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pdf_filepath', sa.String(length=300), nullable=True),
    sa.Column('word_filepath', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('conclusion', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pvp_template_id'], ['pvp_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('reviewer_name', sa.String(length=100), nullable=True),
    sa.Column('reviewer_designation', sa.String(length=100), nullable=True),
    sa.Column('reviewer_signature_url', sa.String(length=500), nullable=True),
    sa.Column('checker_name', sa.String(length=100), nullable=True),
    sa.Column('checker_designation', sa.String(length=100), nullable=True),
    sa.Column('checker_signature_url', sa.String(length=500), nullable=True),
    sa.Column('analyst_name', sa.String(length=100), nullable=True),
    sa.Column('analyst_designation', sa.String(length=100), nullable=True),
    sa.Column('analyst_signature_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amv_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('label_claim', sa.String(length=100), nullable=False),
    sa.Column('active_ingredient', sa.String(length=200), nullable=False),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('instrument_type', sa.String(length=50), nullable=False),
    sa.Column('instrument_params', sa.Text(), nullable=True),
    sa.Column('validation_params', sa.Text(), nullable=True),
    sa.Column('parameters_to_validate', sa.Text(), nullable=True),
    sa.Column('stp_filename', sa.String(length=500), nullable=True),
    sa.Column('method_filename', sa.String(length=500), nullable=True),
    sa.Column('raw_data_filename', sa.String(length=500), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('protocol_generated', sa.Boolean(), nullable=False),
    sa.Column('report_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvr_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pvr_report_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('test_id', sa.String(length=100), nullable=False),
    sa.Column('test_result', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['pvr_report_id'], ['pvr_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pvr_stage_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pvr_report_id', sa.Integer(), nullable=False),
    sa.Column('extracted_stage_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('parameter_name', sa.String(length=200), nullable=False),
    sa.Column('actual_value', sa.String(length=200), nullable=False),
    sa.Column('acceptance_criteria', sa.String(length=200), nullable=False),
    sa.Column('result_status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['extracted_stage_id'], ['pvp_extracted_stages.id'], ),
    sa.ForeignKeyConstraint(['pvr_report_id'], ['pvr_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pvr_stage_results')
    op.drop_table('pvr_data')
    op.drop_table('amv_documents')
    op.drop_table('sub_brands')
    op.drop_table('pvr_reports')
    op.drop_table('pvp_materials')
    op.drop_table('pvp_extracted_stages')
    op.drop_table('pvp_equipment')
    op.drop_table('pvp_criteria')
    op.drop_table('equipment')
    op.drop_table('documents')
    op.drop_table('pvp_templates')
    op.drop_table('companies')
    op.drop_table('activity_logs')
    op.drop_table('users')
    op.execute("DROP INDEX IF EXISTS ix_pv_stage_templates_product_type;")
    op.drop_table('pv_stage_templates')
    # ### end Alembic commands ###
