"""Add word_filepath to PVR_Report

Revision ID: b75094d0a9e4
Revises: 
Create Date: 2025-11-05 22:13:19.671186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75094d0a9e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvr_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_filepath', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pvr_report', schema=None) as batch_op:
        batch_op.drop_column('word_filepath')

    # ### end Alembic commands ###
